### ISSUE TITLE
Not working after upgrade to Ubuntu 19.10

### ISSUE THREAD

**Issue by jradwan** [jradwan/tivo_now_playing#9]
TNPL stopped working after I upgraded my server to Ubuntu 19.10. By re-enabling error logging in index.php, I was able to find the cause of the problem:

```PHP Fatal error:  Uncaught Error: Call to undefined function xml_parser_create() in /usr/local/tivo/tnpl/bin/class_tivo_xml.php:126
Stack trace:
#0 /usr/local/tivo/tnpl/index.php(406): Tivo_XML->parseTiVoXML()
#1 {main}
  thrown in /usr/local/tivo/tnpl/bin/class_tivo_xml.php on line 126

Fatal error: Uncaught Error: Call to undefined function xml_parser_create() in /usr/local/tivo/tnpl/bin/class_tivo_xml.php:126
Stack trace:
#0 /usr/local/tivo/tnpl/index.php(406): Tivo_XML->parseTiVoXML()
#1 {main}
  thrown in /usr/local/tivo/tnpl/bin/class_tivo_xml.php on line 126
```

**Comment by jradwan** [comment]
It turned out I was missing the php7.3-xml package. Once I installed that, TNPL started working again.
